export const FETCH_USERS_STARTED = 'FETCH_USERS_STARTED'
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED'

export const CREATE_USER_STARTED = 'CREATE_USER_STARTED'
export const USER_CREATED = 'USER_CREATED'

export const UPDATE_USER_STARTED = 'UPDATE_USER_STARTED'
export const USER_UPDATED = 'USER_UPDATED'

export const REMOVE_USER_STARTED = 'REMOVE_USER_STARTED'
export const USER_REMOVED = 'USER_REMOVED'

export default {
  FETCH_USERS_STARTED,
  FETCH_USERS_FULFILLED,

  CREATE_USER_STARTED,
  USER_CREATED,

  UPDATE_USER_STARTED,
  USER_UPDATED,

  REMOVE_USER_STARTED,
  USER_REMOVED,
}
